spring.application.name=MIS

spring.datasource.url=jdbc:mysql://root:ztnUOBcmhbHTyIIvOjAXrZASoEYSmEnS@zephyr.proxy.rlwy.net:18612/railway
spring.datasource.username=root
spring.datasource.password=ztnUOBcmhbHTyIIvOjAXrZASoEYSmEnS

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

app.secret-key=oheeE51rexAJfLGXhirN9gPta3JBMCAGkYMs01gIFeSS052sNAUQE5tpvQYylSZz

app.frontend.url=http://localhost:3000
app.base-url:http://localhost:8080/uploads/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikhilpawar278@gmail.com
spring.mail.password=ovssrmaqvepvbfab

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true